### ISSUE TITLE
Develop starter script for Windows

### ISSUE THREAD

**Issue by marble** [t3docs/docker-render-documentation#13]
By private message from Susanne Moog:
"""In your Powershell profile you may want to have:

```
Function Generate-TYPO3-Documentation(
    [String]
    $SourcePath, 
    [String]
    $TargetPath,
    [Boolean]
    $Latex,
    [Boolean]
    $SingleHtml
) {

    if ([String]::IsNullOrEmpty($SourcePath)) {
        $SourcePath = $PWD;
    }

    if ([String]::IsNullOrEmpty($TargetPath)) {
        $TargetPath = "$($PWD)\Documentation-GENERATED-temp\"
    }

    $cmd = "docker run --rm -v $($SourcePath):/PROJECT/:ro -v $($TargetPath):/RESULT/ " + 
           "t3docs/render-documentation makehtml -c make_latex $([int]$Latex)" +
           " -c make_singlehtml $([int]$SingleHtml);"

    Invoke-Expression $cmd
}```

"""

**Comment by n3amil** [comment]
My two cents on this:
-i dont want to edit my powershell profile just to get this stuff working
-i dont want to be forced to use powershell, the docker commands should work from every shell!

to keep the hurdle down for new people contributing to the docs, we should make it as easy as possible to view the generated docs locally, before submitting a PR. The preview on Github is enough for simple text changes, but it just gives me more confidence if i can view the real rendered version.

**Comment by sypets** [comment]
@n3amil The docker commands should work in any shell. But they are quite long and it's tedious to type this. 

But, instead of adding a function to the profile, you could alternatively just create a script file. 

In any case, I think this could be simplified. Makes it easier to understand and use. In 99% of the cases we do not need extra parameters, e.g. something like:

**t3docmake.ps1**

```
docker run --rm -v "$($PWD):/PROJECT/:ro" -v "$($PWD)\Documentation-GENERATED-temp\:/RESULT/" t3docs/render-documentation makehtml;
```

this should be the same as running this under linux:

`docker run --rm -v `pwd`":/PROJECT/:ro" -v `pwd`"/Documentation-GENERATED-temp/:/RESULT/" t3docs/render-documentation makehtml`

P.S. Please also see proposed solution #14 with docker-compose. Probably easier to maintain and execute.

**Comment by marble** [comment]
See https://github.com/t3docs/docker-render-documentation/issues/26#issuecomment-735870076
That `dockrun_t3rd.bat` is working.
