### ISSUE TITLE
Bug: Sphinx extension contrib.googlemaps does not work

### ISSUE THREAD

**Issue by marble** [t3docs/docker-render-documentation#18]
Issue #86741 has been reported by Jan Haffner.

----------------------------------------
Bug #86741: Missing extension manual in english
https://forge.typo3.org/issues/86741

* Author: Jan Haffner
* Status: New
* Priority: Should have
* Assignee: * Category: Manuals
* Target version: * Tags: ----------------------------------------
Only the german manual is rendered:

* 2.0.0 (en is missing)

https://docs.typo3.org/typo3cms/extensions/jh_captcha/

**Comment by TehTux** [comment]
Hi Martin,

thank you for your feedback and the workaround.

Are you sure, that the problem is "sphinxcontrib.googlemaps"?
The german documentation is rendered and use "sphinxcontrib.googlemaps" as well:
https://docs.typo3.org/typo3cms/extensions/jh_captcha/de-de/2.0.0/

I released version 2.1.0 today. I think you checked this after the new release... Is there another problem? I can remove "sphinxcontrib.googlemaps", it's not used now (it's obsolete in my extension).

Best regards,
Jan

**Comment by marble** [comment]
Good answer. I'll check again. Gimme a moment...

**Comment by marble** [comment]
Fixed in master >= v2.0.0
