### ISSUE TITLE
write /dev/stdout: broken pipe

### ISSUE THREAD

**Issue by christian-fries** [t3docs/docker-render-documentation#42]
I wanted to give it a try but when I run `source <(docker run --rm t3docs/render-documentation show-shell-commands)` I get an error message saying `write /dev/stdout: broken pipe` on macOS 10.14.3 with Docker Desktop 2.0.0.3 (Engine: 18.09.2). Therefore `dockrun_t3rdf makehtml` isn't available.

**Comment by sypets** [comment]
Don't know what the problem is, but can you try one or more of the following?

1) Check if Docker Compose workflow works for you: See https://github.com/t3docs/docker-render-documentation#docker-compose  This will use the settings set in the docker-compose.yml file so you do not need to redirect the output of show-shell-commands. 
2) Dump the output into a file instead, e.g. `(docker run --rm t3docs/render-documentation show-shell-commands) > tmp.sh`, then execute that: `. ./tmp.sh`
3) Check which shell you are using, run `echo "$SHELL"`, see https://stackoverflow.com/questions/43417162/which-shell-i-am-using-in-mac. 

I use Linux, never had a problem with these commands. Don't have a Mac available to test, can only guess here. Sorry. The error message indicates that something may be wrong with redirecting the stdout. However, I believe this should work in a bash shell. You might want to check which shell you are using (as described in 3) and use bash instead. 

Please let us know, if any of this works for you, in order to help others.

**Comment by sypets** [comment]
4. Try the html-only version: `source <(docker run --rm t3docs/render-documentation:v1.6.11-html show-shell-commands)`. In that case, you need to run `dockrun_t3rdh makehtml` instead  (notice the h instead of f in rdh). 

Any other error message or something in a logfile that might further help to narrow down the problem?

**Comment by christian-fries** [comment]
I found the following snippet in the #typo3-documentation channel on slack:
```
if ((0)) && [[ ! -e ~/.docker-shell-commands.sh ]]; then true
  echo GENERATE docker run --rm t3docs/render-documentation:v1.6.11-full → ~/.d$
  docker run --rm t3docs/render-documentation:v1.6.11-full  show-shell-commands$
fi
if ((1)) && [[ ! -e ~/.docker-shell-commands.sh ]]; then true
  echo docker pull t3docs/render-documentation:v1.6.11-full
  docker pull t3docs/render-documentation:v1.6.11-full
  echo GENERATE docker run --rm t3docs/render-documentation:v1.6.11-full → ~/.d$
  docker run --rm t3docs/render-documentation:v1.6.11-full  show-shell-commands$
fi
if [[ -e ~/.docker-shell-commands.sh ]]; then true
  source ~/.docker-shell-commands.sh
fi
```

When I add these lines to my `.profile` file, it works. Sadly I cannot tell why but maybe it helps someone else. Seems quite similar to your second provided solution. Btw I'm using bash.

**Comment by sypets** [comment]
Ok, thanks. Yes, that looks like a little more sophisticated variant of solution 2). Running it in the shell profile will execute `show-shell-commands` in the current shell, which is what is trying to be achieved with executing source < (...). This has the additional advantage, that the dockrun_t3rdf command will always be readily available in current shell. 

Actually, we had just simplified the README.rst here a little and before that there was an [alternative in the quickstart](https://github.com/t3docs/docker-render-documentation/tree/1648d85eaf94f06b1988ad8a1177c61dbe9f0d62#quickstart-on-linux). It's always a tradeoff, to have short simple documentation, and document alternatives. But what I think we should do  is keep the quickstart short, but add a link to other alternatives.

Good to know it works for you. Thanks for reporting this and solving the problem yourself. I really would like to know _why_ the source < (...) does not work, maybe someone can shed some light on that, but for now, just use what does work for you.

What I will do, is add some more information to the README.rst. Had already been planning to do that. I opened issues:

* troubleshooting: #43
* add information about adding commands to profile and / or as aliases: #44

**About version (tags):**

For now you can use that version ("v1.6.11-full") as in the snippet, but in the future you should use "latest" (or no version tag which defaults to latest). Just use what you are currently using for now, until we announce a new version.

see: https://hub.docker.com/r/t3docs/render-documentation/tags/

**Comment by marble** [comment]
Problem could not be reproduced.
