### ISSUE TITLE
Documentation does not correspond to output

### ISSUE THREAD

**Issue by thucke** [t3docs/docker-render-documentation#6]
The documentation tells that output will be generated directly under 
> 
> html
> 
> PROJECT/Documentation-GENERATED-temp/Index.html
> singlehtml (all in one file)
> 
> PROJECT/Documentation-GENERATED-temp/singlehtml/Index.html
> build information
> 
> PROJECT/Documentation-GENERATED-temp/_buildinfo/

In reality output ist generated in `PROJECT/Documentation-GENERATED-temp/typo3cms/drafts/project/0.0.0`

**Comment by sypets** [comment]
@thucke Thanks for reporting and sorry about the late reply. I am going through the open issues and will try to fix some documentation related stuff. If you see anything missing, please do feel free to reopen issues or report issues. 

Actually, this has changed again. It is now created in 

**Documentation-GENERATED-temp/Result/project/0.0.0/Index.html**

But the path is still wrong in https://github.com/t3docs/docker-render-documentation#render-your-documentation, number 3. Find the results. 

I would remove the PROJECT (because when we render we must already be in directory PROJECT) and additionally, the subdir is project and not Project. 

I will create a PR to fix.
