### ISSUE TITLE
The image with tag latest produces wrong version with show-shell-commands

### ISSUE THREAD

**Issue by mmunz** [t3docs/docker-render-documentation#95]
To reproduce:

```
$> docker run --rm t3docs/render-documentation:latest show-shell-commands > /tmp/dockrun_t3rdf.tmp
$> source /tmp/dockrun_t3rdf.tmp; rm /tmp/dockrun_t3rdf.tmp; dockrun_t3rd makeall
This function is now defined FOR THIS terminal window:
    dockrun_t3rd
Unable to find image 't3docs/render-documentation:v2.1.0' locally
docker: Error response from daemon: manifest for t3docs/render-documentation:v2.1.0 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

The problem is that a wrong version 2.1.0 is written to the /tmp/dockrun_t3rdf.tmp file while it should be latest:

```
[...]
cmd="$cmd t3docs/render-documentation:v2.1.0"
[...]
```

**Comment by marble** [comment]
This should be fixed in the latest versions with labels "latest", "develop" and "v2.6.1"

- v2-6-1 https://github.com/t3docs/docker-render-documentation/commit/664756a0bf1ba44f7874a033a7afebfb814bd942#diff-3254677a7917c6c01f55212f86c57fbfR6

- latest / master https://github.com/t3docs/docker-render-documentation/blob/master/Dockerfile#L6 

- develop https://github.com/t3docs/docker-render-documentation/blob/develop/Dockerfile#L15
